"""initial schema

Revision ID: 063117b02195
Revises: 
Create Date: 2026-03-30 06:55:08.525259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063117b02195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiales_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('es_medible', sa.Boolean(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('config_consultorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('gastos_fijos', sa.Float(), nullable=True),
    sa.Column('horas_lunes', sa.Float(), nullable=True),
    sa.Column('horas_martes', sa.Float(), nullable=True),
    sa.Column('horas_miercoles', sa.Float(), nullable=True),
    sa.Column('horas_jueves', sa.Float(), nullable=True),
    sa.Column('horas_viernes', sa.Float(), nullable=True),
    sa.Column('horas_sabado', sa.Float(), nullable=True),
    sa.Column('horas_domingo', sa.Float(), nullable=True),
    sa.Column('numero_unidades', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('distribucion_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pct_sueldo', sa.Float(), nullable=True),
    sa.Column('pct_bonos', sa.Float(), nullable=True),
    sa.Column('pct_mcmp', sa.Float(), nullable=True),
    sa.Column('pct_fondo_emergencia', sa.Float(), nullable=True),
    sa.Column('pct_marketing', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('especialistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('comision_pct', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nombre', name='uq_tenant_especialista')
    )
    op.create_table('estrategias_marketing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nombre', name='uq_tenant_estrategia')
    )
    op.create_table('gastos_conceptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nombre', name='uq_tenant_gasto_concepto')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('es_medible', sa.Boolean(), nullable=True),
    sa.Column('costo_paquete', sa.Float(), nullable=True),
    sa.Column('unidades_paquete', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['materiales_master.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nombre', name='uq_tenant_material')
    )
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('comision_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nombre', name='uq_tenant_metodo_pago')
    )
    op.create_table('tratamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('horas_invertidas', sa.Float(), nullable=True),
    sa.Column('precio_paciente', sa.Float(), nullable=True),
    sa.Column('comision_bancaria_pct', sa.Float(), nullable=True),
    sa.Column('comision_especialista_tipo', sa.String(length=20), nullable=True),
    sa.Column('comision_especialista_valor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nombre', name='uq_tenant_tratamiento')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gastos_operativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=True),
    sa.Column('concepto_nombre', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['gastos_conceptos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tratamiento_id', sa.Integer(), nullable=True),
    sa.Column('nombre_tratamiento', sa.String(length=200), nullable=True),
    sa.Column('paciente', sa.String(length=200), nullable=True),
    sa.Column('especialista_id', sa.Integer(), nullable=True),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('comision_bancaria', sa.Float(), nullable=True),
    sa.Column('comision_doctor', sa.Float(), nullable=True),
    sa.Column('factura', sa.Boolean(), nullable=True),
    sa.Column('estrategia_id', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['especialista_id'], ['especialistas.id'], ),
    sa.ForeignKeyConstraint(['estrategia_id'], ['estrategias_marketing.id'], ),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tratamiento_id'], ['tratamientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_doctores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('especialista_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['especialista_id'], ['especialistas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tratamiento_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tratamiento_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['tratamiento_id'], ['tratamientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tratamiento_materiales')
    op.drop_table('pagos_doctores')
    op.drop_table('ingresos')
    op.drop_table('gastos_operativos')
    op.drop_table('users')
    op.drop_table('tratamientos')
    op.drop_table('metodos_pago')
    op.drop_table('materiales')
    op.drop_table('gastos_conceptos')
    op.drop_table('estrategias_marketing')
    op.drop_table('especialistas')
    op.drop_table('distribucion_config')
    op.drop_table('config_consultorio')
    op.drop_table('tenants')
    op.drop_table('materiales_master')
    # ### end Alembic commands ###
