"""add descuento_pct to ingresos

Revision ID: 06d664f87ce3
Revises: f7c4a91d2e08
Create Date: 2026-06-03 16:17:12.789679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d664f87ce3'
down_revision = 'f7c4a91d2e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.drop_column('descuento_pct')

    # ### end Alembic commands ###
