"""add es_impuesto a gastos_conceptos

Revision ID: 18c89f420bc0
Revises: e1f2a3b4c5d6
Create Date: 2026-06-12 21:07:59.217552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers (KEEP the autogenerated revision value)
revision = '18c89f420bc0'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


# Tabla ligera para el backfill de datos
_gc = sa.table(
    "gastos_conceptos",
    sa.column("id", sa.Integer),
    sa.column("tenant_id", sa.Integer),
    sa.column("nombre", sa.String),
    sa.column("tipo", sa.String),
    sa.column("categoria", sa.String),
    sa.column("es_impuesto", sa.Boolean),
)


def upgrade():
    with op.batch_alter_table("gastos_conceptos", schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            "es_impuesto", sa.Boolean(), nullable=False, server_default=sa.false()
        ))

    conn = op.get_bind()

    # 1) Marcar es_impuesto=True en conceptos preexistentes llamados 'Impuestos'
    conn.execute(
        _gc.update()
        .where(_gc.c.nombre == "Impuestos")
        .values(es_impuesto=True)
    )

    # 2) Sembrar el concepto en cada tenant que NO tenga ya uno llamado 'Impuestos'
    tenant_rows = conn.execute(sa.text("SELECT id FROM tenants")).fetchall()
    existing_rows = conn.execute(
        sa.text("SELECT tenant_id FROM gastos_conceptos WHERE nombre = 'Impuestos'")
    ).fetchall()
    tenants_con_impuesto = {r[0] for r in existing_rows}

    faltantes = [
        {
            "tenant_id": r[0],
            "nombre": "Impuestos",
            "tipo": "fijo",
            "categoria": "operativo",
            "es_impuesto": True,
        }
        for r in tenant_rows
        if r[0] not in tenants_con_impuesto
    ]
    if faltantes:
        op.bulk_insert(_gc, faltantes)


def downgrade():
    # Quitar los conceptos sembrados (marcados es_impuesto) y la columna
    conn = op.get_bind()
    conn.execute(_gc.delete().where(_gc.c.es_impuesto == True))  # noqa: E712
    with op.batch_alter_table("gastos_conceptos", schema=None) as batch_op:
        batch_op.drop_column("es_impuesto")
