"""add categorias and m2m with material

Revision ID: 297956e394e0
Revises: 879372f9ee93
Create Date: 2026-04-20 09:33:50.377067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297956e394e0'
down_revision = '879372f9ee93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('material_master_categoria',
    sa.Column('material_master_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['material_master_id'], ['materiales_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_master_id', 'categoria_id')
    )
    op.create_index('ix_material_master_categoria_categoria_id', 'material_master_categoria', ['categoria_id'])
    op.create_table('material_categoria',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', 'categoria_id')
    )
    op.create_index('ix_material_categoria_categoria_id', 'material_categoria', ['categoria_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_material_categoria_categoria_id', table_name='material_categoria', if_exists=True)
    op.drop_table('material_categoria')
    op.drop_index('ix_material_master_categoria_categoria_id', table_name='material_master_categoria', if_exists=True)
    op.drop_table('material_master_categoria')
    op.drop_table('categorias')
    # ### end Alembic commands ###
