"""add lote lote_ubicacion stock_ubicacion

Revision ID: 29d91288c87a
Revises: 8e0bedf92fd2
Create Date: 2026-04-20 09:41:56.943753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d91288c87a'
down_revision = '8e0bedf92fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_inicial', sa.Integer(), nullable=False),
    sa.Column('fecha_surtido', sa.Date(), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('comentarios', sa.String(length=500), nullable=True),
    sa.Column('agotado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('operatorio_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('minimo', sa.Integer(), nullable=True),
    sa.Column('maximo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['operatorio_id'], ['operatorios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'material_id', 'operatorio_id', name='uq_stock_ubicacion')
    )
    op.create_table('lote_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('operatorio_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_restante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['operatorio_id'], ['operatorios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id', 'operatorio_id', name='uq_lote_ubicacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lote_ubicacion')
    op.drop_table('stock_ubicacion')
    op.drop_table('lotes')
    # ### end Alembic commands ###
