"""clip_payments_modules_grace

Revision ID: 47f8e0762a09
Revises: a48578388041
Create Date: 2026-05-15 10:34:52.007100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f8e0762a09'
down_revision = 'a48578388041'
branch_labels = None
depends_on = None


def _has_column(table, column):
    conn = op.get_bind()
    result = conn.execute(sa.text(f"PRAGMA table_info('{table}')"))
    return column in [row[1] for row in result]


def upgrade():
    if not _has_column('payments', 'clip_payment_id'):
        with op.batch_alter_table('payments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('clip_payment_id', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('clip_status', sa.String(length=20), nullable=True))

    if not _has_column('plans', 'modulos'):
        with op.batch_alter_table('plans', schema=None) as batch_op:
            batch_op.add_column(sa.Column('modulos', sa.JSON(), nullable=False, server_default='[]'))

    if not _has_column('subscriptions', 'clip_checkout_id'):
        with op.batch_alter_table('subscriptions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('clip_checkout_id', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('clip_customer_id', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('grace_expires_at', sa.Date(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('grace_expires_at')
        batch_op.drop_column('clip_customer_id')
        batch_op.drop_column('clip_checkout_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('modulos')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('clip_status')
        batch_op.drop_column('clip_payment_id')

    # ### end Alembic commands ###
