"""add dias_alerta_caducidad to config

Revision ID: 52380ddb57f3
Revises: 4881354ca46d
Create Date: 2026-04-20 14:01:19.933102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52380ddb57f3'
down_revision = '4881354ca46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_consultorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_alerta_caducidad', sa.Integer(), nullable=False, server_default=sa.text("'30'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_consultorio', schema=None) as batch_op:
        batch_op.drop_column('dias_alerta_caducidad')

    # ### end Alembic commands ###
