"""add saldo inicial table

Revision ID: 5273f50c868b
Revises: cb654436345d
Create Date: 2026-05-03 10:43:09.586446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5273f50c868b'
down_revision = 'cb654436345d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldos_iniciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'año', name='uq_saldo_inicial_user_año')
    )
    with op.batch_alter_table('saldos_iniciales', schema=None) as batch_op:
        batch_op.create_index('ix_saldo_inicial_user', ['tenant_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldos_iniciales', schema=None) as batch_op:
        batch_op.drop_index('ix_saldo_inicial_user')

    op.drop_table('saldos_iniciales')
    # ### end Alembic commands ###
