"""clip recurring subscription fields

Revision ID: 57b0e5f4c95d
Revises: d9eb4658d000
Create Date: 2026-05-23 23:40:57.186398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b0e5f4c95d'
down_revision = 'd9eb4658d000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clip_price_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('clip_subscription_link', sa.String(length=500), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clip_subscription_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('clip_subscription_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('clip_subscription_link')
        batch_op.drop_column('clip_price_id')

    # ### end Alembic commands ###
