"""add inventario fields to material

Revision ID: 879372f9ee93
Revises: 063117b02195
Create Date: 2026-04-20 09:28:31.666475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879372f9ee93'
down_revision = '063117b02195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expira', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('unidad_inventario', sa.String(length=30), nullable=False, server_default=sa.text("'pieza'")))
        batch_op.add_column(sa.Column('en_inventario', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('materiales_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expira', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('unidad_inventario', sa.String(length=30), nullable=False, server_default=sa.text("'pieza'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales_master', schema=None) as batch_op:
        batch_op.drop_column('unidad_inventario')
        batch_op.drop_column('expira')

    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.drop_column('en_inventario')
        batch_op.drop_column('unidad_inventario')
        batch_op.drop_column('expira')

    # ### end Alembic commands ###
