"""add performance indexes (tenant_id, fecha) en tablas EDR

Acelera los reportes del dashboard y del EDR. Toda consulta del periodo filtra
por (tenant_id, fecha-dentro-de-un-mes); sin estos índices MySQL recorría la
tabla entera en cada request. Va de la mano con el cambio de extract(year/month)
a rangos de fecha sargables (app/engine/accounting.py: filtro_mes), que es lo
que permite a la base usar estos índices.

Revision ID: a7b8c9d0e1f2
Revises: 18c89f420bc0
Create Date: 2026-06-14 00:00:00.000000

"""
from alembic import op


# revision identifiers (KEEP the autogenerated revision value)
revision = 'a7b8c9d0e1f2'
down_revision = '18c89f420bc0'
branch_labels = None
depends_on = None


def upgrade():
    op.create_index(
        "ix_ingresos_tenant_fecha", "ingresos", ["tenant_id", "fecha"]
    )
    op.create_index(
        "ix_gastos_operativos_tenant_fecha",
        "gastos_operativos",
        ["tenant_id", "fecha"],
    )
    op.create_index(
        "ix_pagos_doctores_tenant_fecha",
        "pagos_doctores",
        ["tenant_id", "fecha"],
    )
    op.create_index(
        "ix_pago_comision_ingreso_tenant",
        "pago_comision_ingreso",
        ["tenant_id", "ingreso_id"],
    )


def downgrade():
    op.drop_index("ix_pago_comision_ingreso_tenant", table_name="pago_comision_ingreso")
    op.drop_index("ix_pagos_doctores_tenant_fecha", table_name="pagos_doctores")
    op.drop_index("ix_gastos_operativos_tenant_fecha", table_name="gastos_operativos")
    op.drop_index("ix_ingresos_tenant_fecha", table_name="ingresos")
