"""add performance indexes en tablas de inventario

Tablas que crecen sin parar (lotes, compras, movimientos). Sus listados filtran
por tenant + (material o fecha) y ordenan por fecha desc; sin índice eso es un
full scan. movimientos_recientes (order by fecha desc limit) corre en cada carga
del dashboard, así que ix_movimientos_tenant_fecha es el de mayor impacto.

Revision ID: b8c9d0e1f2a3
Revises: a7b8c9d0e1f2
Create Date: 2026-06-15 00:00:00.000000

"""
from alembic import op


# revision identifiers (KEEP the autogenerated revision value)
revision = 'b8c9d0e1f2a3'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    op.create_index(
        "ix_lotes_tenant_material", "lotes", ["tenant_id", "material_id"]
    )
    op.create_index(
        "ix_compras_tenant_fecha", "compras", ["tenant_id", "fecha"]
    )
    op.create_index(
        "ix_movimientos_tenant_fecha",
        "movimientos_inventario",
        ["tenant_id", "fecha"],
    )


def downgrade():
    op.drop_index("ix_movimientos_tenant_fecha", table_name="movimientos_inventario")
    op.drop_index("ix_compras_tenant_fecha", table_name="compras")
    op.drop_index("ix_lotes_tenant_material", table_name="lotes")
