"""add tasa_impuesto_pct to config_consultorio

Revision ID: c4e1f2a3b6d7
Revises: 06d664f87ce3
Create Date: 2026-06-03 18:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e1f2a3b6d7'
down_revision = '06d664f87ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_consultorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'tasa_impuesto_pct', sa.Float(), nullable=False, server_default='0'
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_consultorio', schema=None) as batch_op:
        batch_op.drop_column('tasa_impuesto_pct')

    # ### end Alembic commands ###
