"""add finanzas personales tables

Revision ID: cb654436345d
Revises: a1b2c3d4e5f6
Create Date: 2026-04-29 21:12:31.444034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb654436345d'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'nombre', name='uq_categoria_personal_user_nombre')
    )
    with op.batch_alter_table('categorias_personales', schema=None) as batch_op:
        batch_op.create_index('ix_categoria_personal_user', ['tenant_id', 'user_id'], unique=False)

    op.create_table('fuentes_ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'nombre', name='uq_fuente_ingreso_user_nombre')
    )
    with op.batch_alter_table('fuentes_ingreso', schema=None) as batch_op:
        batch_op.create_index('ix_fuente_ingreso_user', ['tenant_id', 'user_id'], unique=False)

    op.create_table('metas_ahorro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('monto_objetivo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_objetivo', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metas_ahorro', schema=None) as batch_op:
        batch_op.create_index('ix_meta_ahorro_user', ['tenant_id', 'user_id'], unique=False)

    op.create_table('gastos_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_personales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gastos_personales', schema=None) as batch_op:
        batch_op.create_index('ix_gasto_personal_user_fecha', ['tenant_id', 'user_id', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_gastos_personales_fecha'), ['fecha'], unique=False)

    op.create_table('ingresos_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_ingreso.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingresos_personales', schema=None) as batch_op:
        batch_op.create_index('ix_ingreso_personal_user_fecha', ['tenant_id', 'user_id', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingresos_personales_fecha'), ['fecha'], unique=False)

    op.create_table('presupuestos_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('monto_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_personales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'categoria_id', 'vigente_desde', name='uq_presupuesto_user_cat_fecha')
    )
    with op.batch_alter_table('presupuestos_categoria', schema=None) as batch_op:
        batch_op.create_index('ix_presupuesto_user', ['tenant_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuestos_categoria', schema=None) as batch_op:
        batch_op.drop_index('ix_presupuesto_user')

    op.drop_table('presupuestos_categoria')
    with op.batch_alter_table('ingresos_personales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingresos_personales_fecha'))
        batch_op.drop_index('ix_ingreso_personal_user_fecha')

    op.drop_table('ingresos_personales')
    with op.batch_alter_table('gastos_personales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gastos_personales_fecha'))
        batch_op.drop_index('ix_gasto_personal_user_fecha')

    op.drop_table('gastos_personales')
    with op.batch_alter_table('metas_ahorro', schema=None) as batch_op:
        batch_op.drop_index('ix_meta_ahorro_user')

    op.drop_table('metas_ahorro')
    with op.batch_alter_table('fuentes_ingreso', schema=None) as batch_op:
        batch_op.drop_index('ix_fuente_ingreso_user')

    op.drop_table('fuentes_ingreso')
    with op.batch_alter_table('categorias_personales', schema=None) as batch_op:
        batch_op.drop_index('ix_categoria_personal_user')

    op.drop_table('categorias_personales')
    # ### end Alembic commands ###
