"""promotional plan limits: cupo, fecha, codigo

Revision ID: d5013ec1eadb
Revises: 57b0e5f4c95d
Create Date: 2026-05-24 11:34:55.079514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5013ec1eadb'
down_revision = '57b0e5f4c95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupo_maximo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cupo_usados', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('fecha_inicio_promo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin_promo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('codigo_invitacion', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_plans_codigo_invitacion', ['codigo_invitacion'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counted_in_cupo', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('counted_in_cupo')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint('uq_plans_codigo_invitacion', type_='unique')
        batch_op.drop_column('codigo_invitacion')
        batch_op.drop_column('fecha_fin_promo')
        batch_op.drop_column('fecha_inicio_promo')
        batch_op.drop_column('cupo_usados')
        batch_op.drop_column('cupo_maximo')

    # ### end Alembic commands ###
